GET http://localhost:8081/api/v1/members/6
Accept: application/json
###
GET http://localhost:8081/api/v1/members/11111
Accept: application/json
###

GET http://localhost:8081/api/v1/members
Accept: application/json
###

GET http://localhost:8081/admin/members
Accept: application/json
###

POST http://localhost:8081/api/v1/members
Content-Type: application/json

{
  "number": 30,
  "name": "Vasya M",
  "position": "junior GO"
}
###
POST http://localhost:8081/api/v1/task
Content-Type: application/json

{
  "name": "3024-13000",
  "InParam": 13000,
  "position": "junior GO"
}
###

POST http://localhost:8081/api/v1/tasks/add
Content-Type: application/json
Accept: application/json

{
  "name": "30",
  "InParam": 300
}
###